### ISSUE TITLE
Since UPNP_VERSION_MAJOR was set to 2, Windows 10 BITS client generates event errors

### ISSUE THREAD

**Issue by RMerl** [miniupnp/miniupnp#167] opened 2015-11-27 04:57 UTC
I recently upgraded to the latest miniupnpd code, where UPNP_VERSION_MAJOR was increased from "1" to "2".  Since then, I get these a few times per day in Windows's event log:

```
BITS has encountered an error communicating with an Internet Gateway Device.  Please check that the device is functioning properly. BITS will not attempt to use this device until the next system reboot. Error code: 0x80040500.
```

I tried setting UPNP_VERSION_MAJOR back to "1", created and started a test BITS task, and so far it seems to have resolved the issue.

Test procedure used:

http://blogs.technet.com/b/networking/archive/2008/08/14/how-to-test-the-bits-client-on-your-machine.aspx

Test machine is a Windows 10 desktop.  miniupnpd host is a router running Asuswrt-Merlin.

**Comment by RMerl** [comment] 2015-11-27 05:22
Additional information: this is the generated Event:

https://technet.microsoft.com/en-ca/library/cc734731(v=ws.10).aspx

**Comment by miniupnp** [comment] 2015-11-27 09:12
so with
```
#define UPNP_VERSION_MAJOR      2
#define UPNP_VERSION_MINOR      0
```
the BITS client doesn't work, and with 
```
#define UPNP_VERSION_MAJOR      1
#define UPNP_VERSION_MINOR      1
```
it works ? (no other difference)
Looks like a bug in Windows 10... UDA (UPnP Device Architecture) v2.0 is from September 2014, and Microsoft is a contributor !

Or maybe the UPnP version should not be put in XML descriptions 
```
<root xmlns="urn:schemas-upnp-org:device-1-0">
 <specVersion>
  <major>2</major>
  <minor>0</minor>
 </specVersion>
[...]
```

**Comment by miniupnp** [comment] 2015-11-27 09:16
UPnP-arch-DeviceArchitecture-v2.0.pdf - 2.3 Device description -  p50 : 
_\<specVersion\>
Required. In device templates, defines the lowest version of the architecture on which the device can be implemented. In actual UPnP devices, defines the architecture on which the device is implemented. Contains the following sub elements:
\<major\>
Required. Major version of the UPnP Device Architecture. Shall be 2 for devices implemented on a UPnP 2.0 architecture.
\<minor\>
Required. Minor version of the UPnP Device Architecture. Shall be 0 for devices implemented on a UPnP 2.0 architecture. Shall accurately reflect the version number of the UPnP Device Architecture supported by the device._

**Comment by miniupnp** [comment] 2015-11-27 09:30
there is a doubt that \<specversion\> should not be 2.0 for devices already existing in 1.0 / 1.1 spec ?
Or maybe if the client is only supporting 1.0 ?

please see upnpdescgen.c lines 143-144 (root description) and 979-980 (services)

**Comment by RMerl** [comment] 2015-11-27 14:42
I actually set it to 1.0 rather than 1.1.

I don't know much about the UPNP protocol myself I'm afraid, but a few random thoughts:

1) Could Windows be expecting some additional information to be available in a 2.0 compliant IGD, and miniupnpd isn't exposing that information, leading to the failure?

2) Is this version tied to the IGD version (BTW, enabling IGD2 support causes Windows to fail to recognize the router as being an IGD, but that's a different issue), so unless IGD2 support gets enabled, the UPnP version should be kept at 1.1?

**Comment by charlie2alpha** [comment] 2015-11-27 18:40
Noticed the same error in my Windows 10 logs too, I set major and minor to 1 (UPNP 1.1) and the BITS error dissapeared.

**Comment by miniupnp** [comment] 2015-11-28 09:07
@charlie2alpha so it looks like the Windows 10 BITS client supports UPnP 1.0 and 1.1 but not 2.0 ... 
@RMerl 1) I need some one to test miniupnpd with the UPnP certification tool to know that...
2) UPnP version is not tied to IGD version, you can have IGD2 on UPnP DA v1.1, or IGD v1 on UPnP DA v2.0. It is what I understand from the spec.

http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v2.0.pdf

**Comment by RMerl** [comment] 2015-11-30 18:53
According to this commit, 2.0 requires that both IPv4 and IPv6 be available.  That would explain it, as I keep IPv6 support disabled here.

https://github.com/wl500g/wl500g/commit/8e8443525a538ea1f2c1b91d21d90e67241cdbee

If that comment is accurate, then the version should only be bumped to 2.0 when IPv6 support is enabled (and available on the router?)

**Comment by miniupnp** [comment] 2015-11-30 22:15
Well according to UDA 2.0, the device SHALL support both IPv4 and IPv6, but it may be configured for IPv4 operation only.
If you keep IPv6 support disabled, that is your configuration, so I don't see anyreason not to advertise UPnP/2.0

**Comment by miniupnp** [comment] 2015-11-30 22:27
In an answer to my own question : 
_The architecture version of a root device, all its embedded devices and all its services shall be the same. Version information is communicated in description messages as a backup to the information communicated in discovery messages. This clause explains the format of version information in description messages._ (p44 2 description)

**Comment by miniupnp** [comment] 2015-11-30 22:28
and _Devices and services are allowed to have a version number greater than the major version number of the architecture they are designed for (e.g., “Power:2” is allowed to be designed to work on UDA version 1.0); there is no direct correlation between the version of a device or service template and the architecture version with which it is designed to work._

**Comment by razzfazz** [comment] 2015-12-11 10:19
I believe the specVersion field refers to the UPnP version, not the UDA. It is set to major=1, minor=0 for every single XML example in the IGDv2 specs, and in fact IGDv2 is defined "For UPnP Versions 1.0 and 1.1" only.

**Comment by miniupnp** [comment] 2015-12-11 12:55
IGDv2 is from December 2010,  UDA2.0 February 2015, so it's logical that IGDv2 does not refer to UDA 2.0 but only 1.0 and 1.1

_[...]However UDA version 2.0 is specified as a superset of UDA 1.1 and is thus backwards
compatible with UDA 1.x versions. Therefore UDA 2.0 control points shall maintain
interoperability with UDA 1.x devices. UDA 1.x control points can work with UDA 2.0 devices,
but can’t access the additional functionality specified in UDA 2.0.[...]_

It is explicitly said that UDA 1.x control point can work with UDA 2.0 devices, so that's clearly a bug in the control point if it works with the same device advertising itself as 1.0 or 1.1 and not 2.0

**Comment by miniupnp** [comment] 2015-12-11 13:11
If specVersion is set to 1.0 for every single XML example in IGDv2 spec, it is because IGDv2 can be implemented over UDA v1.0 minimum: 
_\<specVersion\>
Required. In device templates, defines the lowest version of the architecture on which the device can be implemented. In actual UPnP devices, defines the architecture on which the device is implemented._
https://github.com/miniupnp/miniupnp/issues/167#issuecomment-160084137

**Comment by miniupnp** [comment] 2015-12-11 13:14
@RMerl @razzfazz have you reported the problem to Microsoft ?

**Comment by miniupnp** [comment] 2015-12-11 13:42
as a work around, you can use --uda-version=x.x option
https://github.com/miniupnp/miniupnp/commit/9e65fbbded191aa86248a638ad33b5bf59cfc779

**Comment by RMerl** [comment] 2015-12-11 14:37
No, I don't have any line of communication with Microsoft, neither the expertise to debug this.  For now I simply reverted the version back to 1.1.

**Comment by razzfazz** [comment] 2015-12-11 19:53
It's not just Microsoft; Third-party implementations (other than miniupnpc) also stop showing any services when using 2.0.

**Comment by razzfazz** [comment] 2015-12-11 19:54
Interestingly, the test utility I've been using *does* seem to show the devices; it's just the services that seem to be missing.

**Comment by miniupnp** [comment] 2015-12-11 20:11
@razzfazz interesting indeed. What is the test utility you are using ?

**Comment by razzfazz** [comment] 2015-12-11 20:29
http://noeld.com/programs.asp?cat=dstools#upnptest

**Comment by miniupnp** [comment] 2015-12-12 15:29
@razzfazz I contacted No Danjou. His UPNP Test Tool is using Windows UPnP implementation through a COM API, so for the moment it is just Microsoft...

**Comment by razzfazz** [comment] 2015-12-14 15:31
"Just Microsoft" is still going to be a large chunk of your user base, and even if the problem really is on their end, I highly doubt it would ever get fixed on older versions of Windows.

**Comment by miniupnp** [comment] 2015-12-14 15:35
I know. It is even a big problem for UPnP as a whole. If MS Windows UPnP components are incompatible with UDA v2.0, that means this specification implementation will never spread.

**Comment by razzfazz** [comment] 2015-12-14 16:36
Oh, you're a forum member? Does that not get you access to a proper validation suite?

**Comment by miniupnp** [comment] 2015-12-14 16:46
yes but I currently do not have the setup to properly test miniupnpd.
The test suite helped me a lot to improve the compliance in the past. (that's why UPNP_STRICT and so on)

**Closed** 2015-12-19 10:54 UTC

**Comment by miniupnp** [comment] 2016-02-10 19:08
I've finally got an answer from UPnP forum. They discussed the matter with Microsoft which is _"actively investigating the root cause of these issues and next steps involved to address them"_

**Comment by RMerl** [comment] 2016-07-21 04:58
Out of curiosity, I decided to retest this with Windows 10 Insider Review build 14388, and miniupnpd 2.0..  Looks like Microsoft still hasn't sorted this out, the same BITS error still shows up in Event Viewer.

**Comment by miniupnp** [comment] 2016-07-21 06:33
the only feedback I had from microsoft (indirectly) is that they do not consider upnp 2.0 as backward compatible with 1.x.
I don't even think they will ever fix the issue.
