### ISSUE TITLE
miniupnpd on pfSense - interface index not matching error

### ISSUE THREAD

**Issue by Anaerin** [miniupnp/miniupnp#379] opened 2019-06-09 22:47 UTC
miniupnpd is reporting:
```
Jun  7 20:44:46 router miniupnpd[30120]: interface index not matching 9 != 2
```
every minute or so, and the uPNP service can't be seen from the local network.
My configuration (as generated by the pfSense webui) reads:
```
ext_ifname=em0.1000
port=2189
listening_ip=bridge0
bitrate_down=170000000
bitrate_up=20000000
packet_log=yes
secure_mode=yes
presentation_url=https://192.168.0.1:4430/
uuid=51e8b42a-5a15-4bd4-801f-192ed14441b
serial=51E8B42A
model_number=2.4.4-RELEASE
allow 1024-65535 192.168.0.0/24 1024-65535
deny 0-65535 0.0.0.0/0 0-65535
enable_upnp=yes
enable_natpmp=yes
```
My IP configuration is:
```
em0.1000: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 00:21:5a:27:88:2c
        inet6 <censored> prefixlen 64 scopeid 0x7
        inet <censored> netmask 0xfffffc00 broadcast 67.225.27.255
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        vlan: 1000 vlanpcp: 0 parent interface: em0
        groups: vlan
bridge0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 02:bd:b7:a8:27:00
        inet 192.168.0.1 netmask 0xffffff00 broadcast 192.168.0.255
        inet 10.0.0.1 netmask 0xffff0000 broadcast 10.0.255.255
        inet 10.10.10.1 netmask 0xffffffff broadcast 10.10.10.1
        inet6 2001:470:1f17:174::1 prefixlen 64
        inet6 fe80::2bd:b7ff:fea8:2700%bridge0 prefixlen 64 scopeid 0x9
        nd6 options=1<PERFORMNUD>
        groups: bridge
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: re0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 2 priority 128 path cost 55
```
`pfctl -s rules` contains `anchor "miniupnpd" all`
`pfctl -s nat` contains `rdr-anchor "miniupnpd" all`
And the reported package version is `miniupnpd-2.0.20180503,1`, which should be after the fix for #272
So everything appears to be set up correctly. Any suggestions?

**Comment by miniupnp** [comment] 2019-06-09 23:03
`Jun  7 20:44:46 router miniupnpd[30120]: interface index not matching 9 != 2`
means _bridge0_ is interface number 9, but miniupnpd received a SSDP packet on interface number 2...

**Comment by miniupnp** [comment] 2019-06-09 23:08
@Anaerin you should restart _miniupnpd_ with the -d flag to enable debug log

**Comment by Anaerin** [comment] 2019-06-09 23:38
```
 /usr/local/sbin/miniupnpd -f /var/etc/miniupnpd.conf -P /var/run/miniupnpd.pid -d
miniupnpd[25092]: version 2.0 starting NAT-PMP/PCP UPnP-IGD ext if em0.1000 BOOTID=1560122622
miniupnpd[25092]: HTTP listening on port 2189
miniupnpd[25092]: HTTP IPv6 address given to control points : [2001:470:1f17:174::1]
miniupnpd[25092]: setsockopt(udp, IPV6_RECVPKTINFO): Invalid argument
miniupnpd[25092]: Listening for NAT-PMP/PCP traffic on port 5351
miniupnpd[25092]: 160 rt_msg : msglen=160 version=5 type=15
miniupnpd[25092]: unprocessed RTM message type=15
miniupnpd[25092]: 240 rt_msg : msglen=240 version=5 type=1
miniupnpd[25092]:  RTM_ADD
miniupnpd[25092]: 240 rt_msg : msglen=240 version=5 type=1
miniupnpd[25092]:  RTM_ADD
miniupnpd[25092]: 160 rt_msg : msglen=160 version=5 type=15
miniupnpd[25092]: unprocessed RTM message type=15
miniupnpd[25092]: 240 rt_msg : msglen=240 version=5 type=1
miniupnpd[25092]:  RTM_ADD
miniupnpd[25092]: 160 rt_msg : msglen=160 version=5 type=15
miniupnpd[25092]: unprocessed RTM message type=15
miniupnpd[25092]: 160 rt_msg : msglen=160 version=5 type=15
miniupnpd[25092]: unprocessed RTM message type=15
miniupnpd[25092]: 240 rt_msg : msglen=240 version=5 type=1
miniupnpd[25092]:  RTM_ADD
miniupnpd[25092]: 240 rt_msg : msglen=240 version=5 type=1
miniupnpd[25092]:  RTM_ADD
miniupnpd[25092]: 240 rt_msg : msglen=240 version=5 type=1
miniupnpd[25092]:  RTM_ADD
miniupnpd[25092]: level=0 type=20
miniupnpd[25092]: sdl_index = 9  bridge0:2.bd.b7.a8.27.0
miniupnpd[25092]: ST: upnp:rootdevice (ver=0)
miniupnpd[25092]: SSDP M-SEARCH from 192.168.0.64:58884 ST: upnp:rootdevice
miniupnpd[25092]: Single search found
miniupnpd[25092]: SendSSDPResponse(): 0 bytes to 192.168.0.64:58884 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: upnp:rootdevice
USN: uuid:51e8b42a-5a15-4bd4-801f-192ed14441b::upnp:rootdevice
EXT:
SERVER: FreeBSD/11.2-RELEASE-p2 UPnP/1.1 MiniUPnPd/2.0
LOCATION: http://192.168.0.1:2189/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1560122622
BOOTID.UPNP.ORG: 1560122622
CONFIGID.UPNP.ORG: 1337

miniupnpd[25092]: level=0 type=20
miniupnpd[25092]: sdl_index = 2  re0:c4.e9.84.5.41.10
miniupnpd[25092]: interface index not matching 9 != 2
miniupnpd[25092]: ST: upnp:rootdevice (ver=0)
miniupnpd[25092]: SSDP M-SEARCH from 192.168.0.64:58884 ST: upnp:rootdevice
miniupnpd[25092]: Single search found
miniupnpd[25092]: SendSSDPResponse(): 0 bytes to 192.168.0.64:58884 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: upnp:rootdevice
USN: uuid:51e8b42a-5a15-4bd4-801f-192ed14441b::upnp:rootdevice
EXT:
SERVER: FreeBSD/11.2-RELEASE-p2 UPnP/1.1 MiniUPnPd/2.0
LOCATION: http://192.168.0.1:2189/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1560122622
BOOTID.UPNP.ORG: 1560122622
CONFIGID.UPNP.ORG: 1337

miniupnpd[25092]: level=0 type=20
miniupnpd[25092]: sdl_index = 9  bridge0:2.bd.b7.a8.27.0
miniupnpd[25092]: ST: upnp:rootdevice (ver=0)
miniupnpd[25092]: SSDP M-SEARCH from 192.168.0.64:58884 ST: upnp:rootdevice
miniupnpd[25092]: Single search found
miniupnpd[25092]: SendSSDPResponse(): 0 bytes to 192.168.0.64:58884 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: upnp:rootdevice
USN: uuid:51e8b42a-5a15-4bd4-801f-192ed14441b::upnp:rootdevice
EXT:
SERVER: FreeBSD/11.2-RELEASE-p2 UPnP/1.1 MiniUPnPd/2.0
LOCATION: http://192.168.0.1:2189/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1560122622
BOOTID.UPNP.ORG: 1560122622
CONFIGID.UPNP.ORG: 1337

miniupnpd[25092]: level=0 type=20
miniupnpd[25092]: sdl_index = 2  re0:c4.e9.84.5.41.10
miniupnpd[25092]: interface index not matching 9 != 2
miniupnpd[25092]: ST: upnp:rootdevice (ver=0)
miniupnpd[25092]: SSDP M-SEARCH from 192.168.0.64:58884 ST: upnp:rootdevice
miniupnpd[25092]: Single search found
miniupnpd[25092]: SendSSDPResponse(): 0 bytes to 192.168.0.64:58884 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: upnp:rootdevice
USN: uuid:51e8b42a-5a15-4bd4-801f-192ed14441b::upnp:rootdevice
EXT:
SERVER: FreeBSD/11.2-RELEASE-p2 UPnP/1.1 MiniUPnPd/2.0
LOCATION: http://192.168.0.1:2189/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1560122622
BOOTID.UPNP.ORG: 1560122622
CONFIGID.UPNP.ORG: 1337

miniupnpd[25092]: 240 rt_msg : msglen=240 version=5 type=1
miniupnpd[25092]:  RTM_ADD
miniupnpd[25092]: 240 rt_msg : msglen=240 version=5 type=1
miniupnpd[25092]:  RTM_ADD
miniupnpd[25092]: 160 rt_msg : msglen=160 version=5 type=15
miniupnpd[25092]: unprocessed RTM message type=15
miniupnpd[25092]: 240 rt_msg : msglen=240 version=5 type=1
miniupnpd[25092]:  RTM_ADD
miniupnpd[25092]: 160 rt_msg : msglen=160 version=5 type=15
miniupnpd[25092]: unprocessed RTM message type=15
^Cminiupnpd[25092]: shutting down MiniUPnPd
```
As it stands, I have the physical LAN interface (re0, interface 2) and my VPN interface (ovpnsl, interface 10) bridged together through device bridge0 (interface 9), so I am telling miniupnpd to listen on the bridge. It's quite possible miniupnpd is receiving packets on re0 if it's listening on every interface, but it's been told to only listen on bridge0.

**Comment by miniupnp** [comment] 2019-06-09 23:49
it looks like it receives each packet twice. On bridge0 and on re0

**Comment by miniupnp** [comment] 2019-06-10 00:06
miniupnpd is supposed to call IP_ADD_MEMBERSHIP only on the right interface...
but see 08b80d5abda7d7fb93862d960e2a7363df46c53d

**Comment by Anaerin** [comment] 2019-06-10 00:29
And removing the bridge and just connecting direct fixes the problem. So there's something screwy going on with using bridge interfaces.

**Comment by miniupnp** [comment] 2019-06-10 17:59
it might well been something weird going on in the bridge code regarding Multicast group membership.
Multicast is not so much used/tested...

**Comment by miniupnp** [comment] 2019-06-10 21:05
@Anaerin have you tried with the latest miniupnpd version ?
08b80d5abda7d7fb93862d960e2a7363df46c53d may change something...
just to be sure

**Comment by miniupnp** [comment] 2019-10-13 19:12
no answer, closing...

**Comment by devinjdawson** [comment] 2019-10-27 09:37
This is still a problem with the current version of miniupnp packaged with pfSense 2.4.4-RELEASE-p3.

**Comment by devinjdawson** [comment] 2019-10-27 12:45
This problem continues with pfSense 2.5.0-DEVELOPMENT, utilizing FreeBSD 12.0-RELEASE-p10. I believe I am using miniupnpd-2.1.20190210,1.

**Comment by miniupnp** [comment] 2019-10-27 22:27
please try with the current miniupnpd code.
miniupnpd-2.1.20190210 doesn't include 08b80d5

**Comment by amigan** [comment] 2020-04-20 17:23
Using master on FreeBSD 12.1-STABLE, I can confirm that this is still an issue when using bridge interfaces.

**Comment by miniupnp** [comment] 2020-04-20 17:29
@amigan could you give your miniupnpd and network configuration ?

**Comment by amigan** [comment] 2020-04-21 00:41
`ext_ifname=igb0
listening_ip=igb1
listening_ip=wg0
port=5555
enable_natpmp=yes
bitrate_up=50000000
bitrate_down=50000000
system_uptime=yes
clean_ruleset_interval=600
packet_log=no
queue=inet_p2p
uuid=blah
allow 1024-65535 10.68.80.0/24 1024-65535
deny 0-65535 0.0.0.0/0 0-65535
`
igb1 is a member of a bridge with a tap interface.

**Comment by miniupnp** [comment] 2020-04-21 17:31
@amigan  and I guess miniupnpd see it receives the packets on the bridge interface instead of _igb1_ ?

**Comment by miniupnp** [comment] 2020-04-21 18:15
We may have to add code to consider all part of a bridge as the same network interface.

Do anyone know the API to list the bridge members  ? and to know if an interface is a bridge ?

**Comment by amigan** [comment] 2020-04-21 19:02
Yes, that is what appears to be happening.

I can't seem to find any documentation on ioctls for bridge manipulation or anything, but there is https://github.com/freebsd/freebsd/blob/master/sbin/ifconfig/ifbridge.c

**Comment by miniupnp** [comment] 2020-04-27 16:01
I think a better solution is to add the possibility to put the "bridged" interfaces in the configuration

**Comment by amigan** [comment] 2020-04-27 16:44
Perhaps. The immediate problem I see with that solution (at least in my
configuration) is that the bridge does not have an address.Being able to
give get_lan_for_peer() enough information to find the "real" lan_addr
would solve this.

**Comment by miniupnp** [comment] 2020-04-27 17:18
you will have something like 
`listening_ip=igb1 bridge0 tap0` (the 1st interface is the one with the IP address)

**Closed** 2020-04-28 22:09 UTC
Labels: BSD, bug, miniupnpd, waiting for feedback

**Comment by hessuman** [comment] 2021-04-14 18:40
Installed 2.2.1 on FreeBSD 13.0 and changed configuration so that listening_ip lists all the members of the bridge interface (with first one listed having an IP), and can confirm that I no longer receive the index not matching error.
Now, only if the maintainer of the FreeBSD ports would update the included version.

**Comment by RedSector73** [comment] 2021-09-18 02:43
> Installed 2.2.1 on FreeBSD 13.0 and changed configuration so that listening_ip lists all the members of the bridge interface (with first one listed having an IP), and can confirm that I no longer receive the index not matching error.
> Now, only if the maintainer of the FreeBSD ports would update the included version.

Can you explain this in detail, how do I modify this ?
