### ISSUE TITLE
Natpmp port-level unmapping with nftables backend seem to not work

### ISSUE THREAD

**Issue by cculianu** [miniupnp/miniupnp#773] opened 2024-08-09 14:34 UTC
I think the bug is here:

https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/netfilter_nft/nftnlrdr_misc.c#L304

type 1 is for address-level mapping and type 2 is port-level.. I think. And I think this code should be copying over the port to the caller for type 2.. not for type 1.

So later on when you want to unmap on port-level the code doesn't find the correct entry in the table since the port it parsed is always 0...

**Comment by EchterAgo** [comment] 2024-08-09 14:45
I think this is actually the `nftables` backend.

**Comment by cculianu** [comment] 2024-08-09 14:47
Ok ok, corrected the title

**Comment by EchterAgo** [comment] 2024-08-09 15:39
Ref: https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/merge_requests/1837#note_2039007294

**Comment by EchterAgo** [comment] 2024-08-09 15:59
I tested the patch, changing `NFT_REG_1` to `NFT_REG_2` makes destroying the mapping succeed.

**Comment by EchterAgo** [comment] 2024-08-09 16:01
```
Fri Aug  9 22:58:41 2024 daemon.info miniupnpd[28153]: NAT-PMP request received from 192.168.0.40:58695 2bytes
Fri Aug  9 22:58:41 2024 daemon.info miniupnpd[28153]: NAT-PMP public address request
Fri Aug  9 22:58:41 2024 daemon.info miniupnpd[28153]: NAT-PMP request received from 192.168.0.40:58695 12bytes
Fri Aug  9 22:58:41 2024 daemon.info miniupnpd[28153]: NAT-PMP port mapping request : 23423->192.168.0.40:23423 tcp lifetime=3600s
Fri Aug  9 22:58:41 2024 daemon.debug miniupnpd[28153]: UPnP permission rule 0 matched : port mapping accepted
Fri Aug  9 22:58:41 2024 daemon.debug miniupnpd[28153]: Check protocol tcp for port 23423 on ext_if pppoe-3bb 27.130.255.115, 73FF821B
Fri Aug  9 22:58:41 2024 daemon.debug miniupnpd[28153]: timestamp entry added (23423, 6, 14194)
Fri Aug  9 22:58:41 2024 daemon.debug miniupnpd[28153]: table_cb(0x7feafb8800, 0x7feafb9800) fw4 upnp_forward 2
Fri Aug  9 22:58:41 2024 daemon.debug miniupnpd[28153]: rule with label 'NAT-PMP 23423 tcp' is not a IGD pinhole
Fri Aug  9 22:58:47 2024 daemon.info miniupnpd[28153]: NAT-PMP request received from 192.168.0.40:58695 12bytes
Fri Aug  9 22:58:47 2024 daemon.info miniupnpd[28153]: NAT-PMP port mapping request : 0->192.168.0.40:23423 tcp lifetime=0s
Fri Aug  9 22:58:47 2024 daemon.debug miniupnpd[28153]: table_cb(0x7feafb86a0, 0x7feafb96a0) fw4 upnp_prerouting 1
Fri Aug  9 22:58:47 2024 daemon.debug miniupnpd[28153]: parse_rule_nat: proto_min_reg 2 : 00007f5b => 23423
Fri Aug  9 22:58:47 2024 daemon.debug miniupnpd[28153]: timestamp entry found (23423, 6, 14194)
Fri Aug  9 22:58:47 2024 daemon.debug miniupnpd[28153]: 0 6 23423->'192.168.0.40':23423 'NAT-PMP 23423 tcp'
Fri Aug  9 22:58:47 2024 daemon.info miniupnpd[28153]: NAT-PMP TCP port 23423 mapping removed
Fri Aug  9 22:58:47 2024 daemon.debug miniupnpd[28153]: rule with label 'NAT-PMP 23423 tcp' is not a IGD pinhole
```

the internal port is now listed correctly when unmapping.

**Comment by miniupnp** [comment] 2024-08-10 20:57
I think this is a duplicate of #768 and I have fixed this bug in commit https://github.com/miniupnp/miniupnp/commit/792757fb2731eaf3d1781ca3be7551226c829241 of branch [768-fix-nft-parse_rule_nat](https://github.com/miniupnp/miniupnp/tree/)

@EchterAgo @cculianu Could you test this branch and confirm it fixes the issue ?
Thank you very much !

**Comment by EchterAgo** [comment] 2024-08-11 11:06
In the commit you are setting `nat_port` without checking for `NFT_REG_1`. I already tested with checking for `NFT_REG_2`, so I'm pretty sure your commit will fix the issue. I'll try to check with the commit but I need some time.

**Comment by EchterAgo** [comment] 2024-08-11 11:17
Ok, I tested 792757fb2731eaf3d1781ca3be7551226c829241 applied to OpenWRT's `miniupnpd` 2.3.7 package and the mapping gets removed, so I think this can be closed. Thanks!

**Closed** 2024-08-11 23:16 UTC
Labels: miniupnpd, duplicate, linux, netfilter_nftables
