### ISSUE TITLE
Thu May 13 23:22:37 2021 daemon.notice miniupnpd[5802]: private/reserved address checking is ignore

### ISSUE THREAD

**Issue by vpei** [miniupnp/miniupnp#546] opened 2021-05-13 15:40 UTC
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:52 2021 daemon.err miniupnpd[14381]: sendto(udp_notify=8, [10:0:4::254]): Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=461, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=461, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=477, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=473, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=461, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=459, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=406, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=445, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=406, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=465, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=406, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=469, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=397, dest=[ff0e::c]:1900): sendto: Address not available
Thu May 13 23:44:53 2021 daemon.err miniupnpd[14381]: try_sendto(sock=8, len=461, dest=[ff05::c]:1900): sendto: Address not available

**Where is this in correctly set up ?**

**Comment by pali** [comment] 2021-05-16 16:09
Duplicate of #542

@miniupnp I think you can close this issue and also #511.

**Closed** 2021-05-18 01:35 UTC
