### ISSUE TITLE
OpenBSD IPv6, HTTP Peer is not from Lan

### ISSUE THREAD

**Issue by gizahNL** [miniupnp/miniupnp#227] opened 2017-01-29 14:29 UTC
Compiled 2.0-current source (as downloaded from the download section on the site) with options ipv6 igd2 and leasefile enabled on OpenBSD 6.0 

When using miniupnpc (ubuntu, standard from packages) to find an controlpoint the connection is disconnected due to  'HTTP is not from LAN'

Logs:
# miniupnpd -f /etc/miniupnpd.conf -d 
miniupnpd[22643]: Reloading rules from lease file
miniupnpd[22643]: could not open lease file: /var/log/upnp.leases
miniupnpd[22643]: version 2.0 starting NAT-PMP/PCP UPnP-IGD ext if pppoe0 BOOTID=1485699852
miniupnpd[22643]: HTTP listening on port 43485
miniupnpd[22643]: HTTP IPv6 address given to control points : [2001:984:a1fc:1:215:17ff:fe3e:e09e]
miniupnpd[22643]: Listening for NAT-PMP/PCP traffic on port 5351
miniupnpd[22643]: rule with label 'NAT-PMP 51413 tcp' is not a IGD pinhole
miniupnpd[22643]: rule with label 'NAT-PMP 51413 tcp' is not a IGD pinhole
miniupnpd[22643]: rule with label 'NAT-PMP 51413 tcp' is not a IGD pinhole
miniupnpd[22643]: Received UDP Packet (IPv6)
miniupnpd[22643]: get_lan_for_peer() looking for LAN interface index=11
miniupnpd[22643]: ifname=vlan1 index=11 str=10.0.1.1 addr=0a000101 mask=ffffff00
miniupnpd[22643]: ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1 (ver=1)
miniupnpd[22643]: SSDP M-SEARCH from [fe80::5ec5:d4ff:fecc:66a4%vlan1]:54294 ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
miniupnpd[22643]: Single search found
miniupnpd[22643]: SendSSDPResponse(): 0 bytes to [fe80::5ec5:d4ff:fecc:66a4%vlan1]:54294 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
USN: uuid:6b9a5b44-114c-49c2-af26-3bfdc38d40ce::urn:schemas-upnp-org:device:InternetGatewayDevice:1
EXT:
SERVER: OpenBSD/6.0 UPnP/1.1 MiniUPnPd/2.0
LOCATION: http://[2001:984:a1fc:1:215:17ff:fe3e:e09e]:43485/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1485699852
BOOTID.UPNP.ORG: 1485699852
CONFIGID.UPNP.ORG: 1337

miniupnpd[22643]: rule with label 'NAT-PMP 51413 tcp' is not a IGD pinhole
miniupnpd[22643]: rule with label 'NAT-PMP 51413 tcp' is not a IGD pinhole
miniupnpd[22643]: rule with label 'NAT-PMP 51413 tcp' is not a IGD pinhole
miniupnpd[22643]: 192 rt_msg : msglen=192 version=5 type=11
miniupnpd[22643]: unprocessed RTM message type=11
miniupnpd[22643]: rule with label 'NAT-PMP 51413 tcp' is not a IGD pinhole
miniupnpd[22643]: read l=256 seq=1 pid=22643   sizeof(struct rt_msghdr)=96
miniupnpd[22643]: type=1 sa_len=28 sa_family=24 [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:0
miniupnpd[22643]: type=2 sa_len=16 sa_family=65 unknown address family 65
miniupnpd[22643]: type=4 sa_len=102 sa_family=164 unknown address family 164
miniupnpd[22643]: type=16 sa_len=23 sa_family=255 unknown address family 255
miniupnpd[22643]: error parsing ROUTE response message
miniupnpd[22643]: HTTP peer [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:43014 is not from a LAN, closing the connection
miniupnpd[22643]: rule with label 'NAT-PMP 51413 tcp' is not a IGD pinhole
miniupnpd[22643]: 256 rt_msg : msglen=256 version=5 type=4
miniupnpd[22643]:  RTM_GET
miniupnpd[22643]: rule with label 'NAT-PMP 51413 tcp' is not a IGD pinhole
^Cminiupnpd[22643]: shutting down MiniUPnPd
# 

gijs@gijs-ThinkPad-T440s:~$ upnpc -6 -m wlan0 -S 
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://[2001:984:a1fc:1:215:17ff:fe3e:e09e]:43485/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

No valid UPNP Internet Gateway Device found.

Config file:

# cat /etc/miniupnpd.conf                                                                                                                                                                                  
ext_ifname=pppoe0
listening_ip=vlan1
enable_natpmp=yes
lease_file=/var/log/upnp.leases
bitrate_up=524288000
bitrate_down=524288000
system_uptime=yes
notify_interval=60
clean_ruleset_interval=600
uuid=6b9a5b44-114c-49c2-af26-3bfdc38d40ce
allow 1024-65535 10.0.1.1/24 1024-65535
deny 0-65535 0.0.0.0/0 0-65535

**Comment by miniupnp** [comment] 2017-01-30 14:05
the issue is somewhere there : https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/bsd/getroute.c#L95
```
miniupnpd[22643]: read l=256 seq=1 pid=22643 sizeof(struct rt_msghdr)=96
miniupnpd[22643]: type=1 sa_len=28 sa_family=24 [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:0
miniupnpd[22643]: type=2 sa_len=16 sa_family=65 unknown address family 65
miniupnpd[22643]: type=4 sa_len=102 sa_family=164 unknown address family 164
miniupnpd[22643]: type=16 sa_len=23 sa_family=255 unknown address family 255
miniupnpd[22643]: error parsing ROUTE response message
```
it is supposed to get the network index interface there : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/bsd/getroute.c#L131

**Comment by miniupnp** [comment] 2017-01-30 14:12
please try
```
$ ./testgetroute 2a00:1450:400c:c04::68
testgetroute: calling get_src_for_route_to(0xcfbd7e38, NULL, NULL, 0xcfbd7e34)
testgetroute: read l=196 seq=1 pid=24315   sizeof(struct rt_msghdr)=88
testgetroute: type=1 sa_len=28 sa_family=24 [::]:0
testgetroute: type=2 sa_len=28 sa_family=24 [2a01:e35:139a:b0b0::1]:0
testgetroute: type=4 sa_len=0 sa_family=0 unknown address family 0
testgetroute: type=16 sa_len=20 sa_family=18 index=2 type=6 xl1:0.10.5a.55.f2.4e
testgetroute: type=32 sa_len=28 sa_family=24 [2a01:e35:139a:b0b0::2]:0
testgetroute: get_src_for_route_to() returned 0
testgetroute: index=2
testgetroute: calling get_src_for_route_to(0xcfbd7e38, 0xcfbd7e40, 0xcfbd7e30(16), 0xcfbd7e34)
testgetroute: read l=196 seq=1 pid=24315   sizeof(struct rt_msghdr)=88
testgetroute: type=1 sa_len=28 sa_family=24 [::]:0
testgetroute: type=2 sa_len=28 sa_family=24 [2a01:e35:139a:b0b0::1]:0
testgetroute: type=4 sa_len=0 sa_family=0 unknown address family 0
testgetroute: type=16 sa_len=20 sa_family=18 index=2 type=6 xl1:0.10.5a.55.f2.4e
testgetroute: type=32 sa_len=28 sa_family=24 [2a01:e35:139a:b0b0::2]:0
testgetroute: get_src_for_route_to() returned 0
testgetroute: src=[2a01:e35:139a:b0b0::2]:0
testgetroute: index=2
```
something is wrong with the parsing on your machine

**Comment by gizahNL** [comment] 2017-01-30 16:20
./testgetroute 2a00:1450:400c:c04::68                                        
testgetroute: calling get_src_for_route_to(0x7f7ffffd42a0, NULL, NULL, 0x7f7ffffd42dc)
testgetroute: read l=264 seq=1 pid=50169   sizeof(struct rt_msghdr)=96
testgetroute: type=1 sa_len=28 sa_family=24 [::]:0
testgetroute: type=2 sa_len=82 sa_family=65 unknown address family 65
testgetroute: type=4 sa_len=0 sa_family=0 unknown address family 0
testgetroute: type=16 sa_len=0 sa_family=0 unknown address family 0
testgetroute: type=32 sa_len=0 sa_family=0 unknown address family 0
testgetroute: type=128 sa_len=0 sa_family=0 unknown address family 0
testgetroute: get_src_for_route_to() returned -1
testgetroute: calling get_src_for_route_to(0x7f7ffffd42a0, 0x7f7ffffd42a8, 0x7f7ffffd42d0(16), 0x7f7ffffd42dc)
testgetroute: read l=264 seq=1 pid=50169   sizeof(struct rt_msghdr)=96
testgetroute: type=1 sa_len=28 sa_family=24 [::]:0
testgetroute: type=2 sa_len=82 sa_family=65 unknown address family 65
testgetroute: type=4 sa_len=0 sa_family=0 unknown address family 0
testgetroute: type=16 sa_len=0 sa_family=0 unknown address family 0
testgetroute: type=32 sa_len=0 sa_family=0 unknown address family 0
testgetroute: type=128 sa_len=0 sa_family=0 unknown address family 0
testgetroute: get_src_for_route_to() returned -1


one from my own network (the machine its running on:
./testgetroute 2001:984:a1fc:1::1                                            
testgetroute: calling get_src_for_route_to(0x7f7ffffdd870, NULL, NULL, 0x7f7ffffdd8ac)
testgetroute: read l=256 seq=1 pid=8277   sizeof(struct rt_msghdr)=96
testgetroute: type=1 sa_len=28 sa_family=24 [2001:984:a1fc:1::1]:0
testgetroute: type=2 sa_len=239 sa_family=190 unknown address family 190
testgetroute: error parsing ROUTE response message
testgetroute: get_src_for_route_to() returned -1
testgetroute: calling get_src_for_route_to(0x7f7ffffdd870, 0x7f7ffffdd878, 0x7f7ffffdd8a0(16), 0x7f7ffffdd8ac)
testgetroute: read l=256 seq=1 pid=8277   sizeof(struct rt_msghdr)=96
testgetroute: type=1 sa_len=28 sa_family=24 [2001:984:a1fc:1::1]:0
testgetroute: type=2 sa_len=239 sa_family=190 unknown address family 190
testgetroute: error parsing ROUTE response message
testgetroute: get_src_for_route_to() returned -1


one trying towards my laptop:
 ./testgetroute 2001:984:a1fc:1:99c9:f216:8c14:92ff                           
testgetroute: calling get_src_for_route_to(0x7f7fffff49c0, NULL, NULL, 0x7f7fffff49fc)
testgetroute: read l=256 seq=1 pid=50472   sizeof(struct rt_msghdr)=96
testgetroute: type=1 sa_len=28 sa_family=24 [2001:984:a1fc:1::]:0
testgetroute: type=2 sa_len=239 sa_family=190 unknown address family 190
testgetroute: error parsing ROUTE response message
testgetroute: get_src_for_route_to() returned -1
testgetroute: calling get_src_for_route_to(0x7f7fffff49c0, 0x7f7fffff49c8, 0x7f7fffff49f0(16), 0x7f7fffff49fc)
testgetroute: read l=256 seq=1 pid=50472   sizeof(struct rt_msghdr)=96
testgetroute: type=1 sa_len=28 sa_family=24 [2001:984:a1fc:1::]:0
testgetroute: type=2 sa_len=239 sa_family=190 unknown address family 190
testgetroute: error parsing ROUTE response message
testgetroute: get_src_for_route_to() returned -1

**Comment by gizahNL** [comment] 2017-01-30 16:26
I tried compiling and running testroute on my FreeBSD rig, where it functions fine, my best guess is that there is a difference in the output between OpenBSD (6.0) and FreeBSD

**Comment by miniupnp** [comment] 2017-01-30 16:39
it was tested and run fine with OpenBSD 4.3 i386

**Comment by miniupnp** [comment] 2017-01-30 16:46
please test with https://github.com/miniupnp/miniupnp/tree/test_getroute

**Comment by miniupnp** [comment] 2017-01-30 17:03
@gizahNL I guess your OpenBSD 6.0 machine is 64bit, right ?

**Comment by gizahNL** [comment] 2017-01-30 17:04
# ./testgetroute 2001:984:a1fc:1:5ec5:d4ff:fecc:66a4                                                                                                                                                       
testgetroute: calling get_src_for_route_to(0x7f7ffffe4880, NULL, NULL, 0x7f7ffffe48bc)
testgetroute: read l=256 seq=1 pid=74785   sizeof(struct rt_msghdr)=96
testgetroute: offset=  0 type= 1 sa_len=28 sa_family=24 [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:0
testgetroute: offset= 28 type= 2 sa_len=16 sa_family=65 unknown address family 65
testgetroute: offset= 44 type= 4 sa_len=102 sa_family=164 unknown address family 164
testgetroute: offset=146 type=16 sa_len=0 sa_family=0 unknown address family 0
testgetroute: offset=154 type=32 sa_len=0 sa_family=0 unknown address family 0
testgetroute: get_src_for_route_to() returned -1
testgetroute: calling get_src_for_route_to(0x7f7ffffe4880, 0x7f7ffffe4888, 0x7f7ffffe48b0(16), 0x7f7ffffe48bc)
testgetroute: read l=256 seq=1 pid=74785   sizeof(struct rt_msghdr)=96
testgetroute: offset=  0 type= 1 sa_len=28 sa_family=24 [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:0
testgetroute: offset= 28 type= 2 sa_len=16 sa_family=65 unknown address family 65
testgetroute: offset= 44 type= 4 sa_len=102 sa_family=164 unknown address family 164
testgetroute: offset=146 type=16 sa_len=0 sa_family=0 unknown address family 0
testgetroute: offset=154 type=32 sa_len=0 sa_family=0 unknown address family 0
testgetroute: get_src_for_route_to() returned -1

**Comment by miniupnp** [comment] 2017-01-30 17:06
please update the branch :) does https://github.com/miniupnp/miniupnp/commit/88d59b6556912d062cd70d816cf847a93b56cf23 fixes it ?

**Comment by gizahNL** [comment] 2017-01-30 17:08
this does seem a lot like more healthy output:
# ./testgetroute 2001:984:a1fc:1:5ec5:d4ff:fecc:66a4                                                                        
testgetroute: calling get_src_for_route_to(0x7f7ffffc79a0, NULL, NULL, 0x7f7ffffc79dc)
testgetroute: read l=256 seq=1 pid=53447   sizeof(struct rt_msghdr)=96
testgetroute: offset=  0 type= 1 sa_len=28 sa_family=24 [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:0
testgetroute: offset= 32 type= 2 sa_len=32 sa_family=18 index=11 type=6 5c.c5.d4.cc.66.a4
testgetroute: offset= 64 type= 4 sa_len=28 sa_family=24 [ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff]:0
testgetroute: offset= 96 type=16 sa_len=32 sa_family=18 index=11 type=6 vlan1:0.15.17.3e.e0.9e
testgetroute: offset=128 type=32 sa_len=28 sa_family=24 [2001:984:a1fc:1::1]:0
testgetroute: get_src_for_route_to() returned 0
testgetroute: index=11
testgetroute: calling get_src_for_route_to(0x7f7ffffc79a0, 0x7f7ffffc79a8, 0x7f7ffffc79d0(16), 0x7f7ffffc79dc)
testgetroute: read l=256 seq=1 pid=53447   sizeof(struct rt_msghdr)=96
testgetroute: offset=  0 type= 1 sa_len=28 sa_family=24 [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:0
testgetroute: offset= 32 type= 2 sa_len=32 sa_family=18 index=11 type=6 5c.c5.d4.cc.66.a4
testgetroute: offset= 64 type= 4 sa_len=28 sa_family=24 [ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff]:0
testgetroute: offset= 96 type=16 sa_len=32 sa_family=18 index=11 type=6 vlan1:0.15.17.3e.e0.9e
testgetroute: offset=128 type=32 sa_len=28 sa_family=24 [2001:984:a1fc:1::1]:0
testgetroute: get_src_for_route_to() returned 0
testgetroute: src=[2001:984:a1fc:1::1]:0
testgetroute: index=11


Also, yes I am on the amd64 branch of OpenBSD. Thank you for the quick fix!

**Comment by miniupnp** [comment] 2017-01-30 17:11
fixed by https://github.com/miniupnp/miniupnp/commit/88d59b6556912d062cd70d816cf847a93b56cf23

**Closed by miniupnp** 2017-01-30 17:11 UTC
