### ISSUE TITLE
The latest updated version does not work properly.There are no active redirects.

### ISSUE THREAD

**Issue by vpei** [miniupnp/miniupnp#556] opened 2021-08-03 14:12 UTC
The latest updated version does not work properly.There are no active redirects.

301-ext_ip_reserved_ignore.patch   is removed.

**Comment by vpei** [comment] 2021-08-10 14:24
miniupnpd 2.2.2-3 does not work properly.
miniupnpd 2.2.2-2 works fine.

openwrt linux 5.4.138 or 5.4.139 ....

**Comment by miniupnp** [comment] 2021-08-11 12:31
I don't understand what you are talking about.
Shouldn't you ask the openwrt package maintainer ?

**Comment by Neustradamus** [comment] 2021-08-17 15:22
To follow this bug

**Comment by openips** [comment] 2021-08-18 00:11
To follow this bug

**Comment by miniupnp** [comment] 2021-08-18 09:06
Please explain clearly what is wrong with miniupnpd distribution and what should be fixed.

**Comment by openips** [comment] 2021-08-18 12:56
> Please explain clearly what is wrong with miniupnpd distribution and what should be fixed.

https://github.com/openwrt/packages/issues/16268

**Comment by pali** [comment] 2021-08-19 20:42
Please explain _clearly_ what is wrong with **miniupnpd** (not openwrt) distribution and what should be fixed.

**Comment by openips** [comment] 2021-08-20 02:58
301-ext_ip_reserved_ignore.patch is missing

**Comment by pali** [comment] 2021-08-20 08:04
Could you please explain _clearly_ what is wrong with **miniupnpd** (not openwrt) distribution?

And could you please explain what should be _fixed_?

**Comment by openips** [comment] 2021-08-23 01:56
only find the bug in openwrt

**Comment by pali** [comment] 2021-08-23 11:12
I'm asking the last time, could you please **clearly** describe and explain what is wrong with **miniupnpd**?

This is not an openwrt bugtracker and openwrt bugs are not being solved here. If there is no issue with miniupnpd, this ticket can be closed and report openwrt bug to openwrt bugtracker.

**Comment by openips** [comment] 2021-08-25 13:16
i have 3 wan. one have public ipv4 ,the other 2 have private ipv4,and 1 public ipv6
the upnp use the port with 1 privat ipv4 and 1 public ipv6 to work
The latest updated version does not work properly.but 2.2.1 worked very well

**Closed** 2021-08-30 23:04 UTC
Labels: miniupnpd, waiting for feedback, linux

**Comment by Neustradamus** [comment] 2021-09-16 09:41
There is a new patch from @ptpt52:
- https://github.com/openwrt/packages/pull/16011#issuecomment-920538698

It replaces the old 301-ext_ip_reserved_ignore.patch.

Tested by @openips!

**Comment by pali** [comment] 2021-09-16 14:13
@Neustradamus what you are mumbling here? This github issue was reported for something which is not a bug in miniupnpd. Just OpenWRT generated wrong configuration file for miniupnpd and obviously miniupnpd cannot work if you start it with incorrect command line options or configuration file. So it purely bug in OpenWRT.
