### ISSUE TITLE
miniupnp minor issue bug?

### ISSUE THREAD

**Issue by Salvora** [miniupnp/miniupnp#567] opened 2021-09-23 15:51 UTC
Hello guys,
We have been trying to figure out an issue with the Home Assistant folks regarding the upnp behavior of an Asus router running merlin fw which uses miniupnpd.
https://github.com/RMerl/asuswrt-merlin.ng/tree/master/release/src/router
The details regarding it can be found in here https://github.com/home-assistant/core/issues/55783.
Basically when the internet connection is down, the router gives inexplicable upnp response like this.
```
<NewExternalIPAddress>schemas.upnp.org��i����</NewExternalIPAddress>
```
Any input it appreciated.

**Comment by pali** [comment] 2021-09-23 20:26
Is this problem available in the latest unmodified version of miniupnpd from miniupnpd git master branch?

**Comment by Salvora** [comment] 2021-09-23 21:39
It is in the v2.2.0
https://github.com/RMerl/asuswrt-merlin.ng/blob/master/release/src/router/miniupnpd/VERSION

**Comment by pali** [comment] 2021-09-23 21:42
So update to the latest version from miniupnpd git master branch and check if this issue is fixed or not.

**Comment by Salvora** [comment] 2021-09-26 20:06
I have seriously tried but apparently it is not possible to update a library in the router firmware. At least, it is not within my ability. I am open to debugging if anyone can show me the way.

**Comment by Salvora** [comment] 2021-10-06 18:49
Right now, there is nothing I can do other than wait for the new router fw to be released with updated miniupnd client. This might take a long while. The changelog for 2.2.1 might have fixed the issue. Can't say for sure without trying.
```
2021/06/18:
  Fails on config parsing and init errors.
  print errors during init to both syslog and stderr.
```

**Comment by miniupnp** [comment] 2021-10-08 18:32
https://github.com/miniupnp/miniupnp/commit/3a87be33e797ba947b2b2a5f8d087f6c3ff4d93e might change the behavior on getExternalIpAddress

**Comment by miniupnp** [comment] 2022-10-15 11:36
I'm closing, please reopen if the issue is still there with miniupnpd 2.3.0

**Closed by miniupnp** 2022-10-15 11:36 UTC
Labels: miniupnpd, waiting for feedback
