### ISSUE TITLE
Won't record neither show my upnp redirections

### ISSUE THREAD

**Issue by lucaszanella** [miniupnp/miniupnp#329] opened 2018-09-23 22:21 UTC
I'm using miniupnp in raspberry pi. It looks like every command I call, it just lists UPNP devices without doing what I asked. See:

```
pi@raspberrypi:~ $ upnpc -e 'SSH on Raspberry Pi' -r 2324 TCP
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:5000/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

 desc: http://192.168.100.3:8888/WFADeviceDesc.xml
 st: upnp:rootdevice


pi@raspberrypi:~ $ upnpc -l
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:5000/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

 desc: http://192.168.100.3:8888/WFADeviceDesc.xml
 st: upnp:rootdevice



```

**Comment by miniupnp** [comment] 2018-09-24 13:38
`(c) 2005-2014 `
it looks like you're using a very old version

**Comment by miniupnp** [comment] 2018-09-27 09:03
@lucaszanella are you reproducing the issue using altest code from the repository ?

**Comment by miniupnp** [comment] 2019-02-12 15:08
I'm closing after a few month without answer

**Closed by miniupnp** 2019-02-12 15:08 UTC
Labels: miniupnpc, waiting for feedback
