### ISSUE TITLE
Issue with indirectly connected lan networks

### ISSUE THREAD

**Issue by shinygecko** [miniupnp/miniupnp#629] opened 2022-10-09 05:38 UTC
I am having difficulty overriding the lan network segment for upnp in my setup involving a l3 switch behind opnnsense.

Transit network from opnsense to l3 switch is 10.10.10.0/30 (vmx1)

l3 switch has my actual subnets for example 10.0.0.0/24

I have tried adding a 2nd range for the listening ip however i still get the message 
miniupnpd 43008 - - HTTP peer 10.0.0.102:38974 is not from a LAN, closing the connection

I then found another issue very close to mine here mentioning that vmx1/8 could be used for example and this actually does work sort of. I get the message below when the requests hit but no further action is processed for upnp.

miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38624 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38626 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38622 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38636 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38628 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38630 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38632 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38634 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38638 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38640 : GET /WANIPCn.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38642 : GET /WANIPCn.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38644 : GET /WANIPCn.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38646 : GET /WANCfg.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38648 : GET /WANCfg.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38650 : GET /WANCfg.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38652 : GET /L3F.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38656 : GET /L3F.xml (HTTP/1.1)
miniupnpd 12388 - - Host: 10.10.10.1:2189
miniupnpd 12388 - - HTTP REQUEST from 10.0.0.102:38654 : GET /L3F.xml (HTTP/1.1)

##CONFIG##

root@OPNsense:~ # more /var/etc/miniupnpd.conf
ext_ifname=vmx0
port=2189
listening_ip=vmx1
listening_ip=10.0.0.0/24
secure_mode=yes
packet_log=yes
system_uptime=yes
presentation_url=https://10.10.10.1/
uuid=0e92e950-9c91-46f9-7d35-bd43c54af59
serial=0E92E950
model_number=22.7.5
allow 1024-65535 10.0.0.0/24 1024-65535
deny 0-65535 0.0.0.0/0 0-65535
enable_upnp=yes
enable_natpmp=no
clean_ruleset_interval=600
min_lifetime=120
max_lifetime=86400

Any help in debugging this would be greatly appreciated.

Also may of been fixed here?
https://github.com/opnsense/plugins/pull/3096

**Comment by miniupnp** [comment] 2022-10-09 08:56
maybe `listening_ip=vmx1/8` should work...
What client are you using ? Maybe it doesn't like that the UPnP IGD is not on the default gateway IP.

**Comment by shinygecko** [comment] 2022-10-09 17:01
That particular client is just an LG TV, i have testing with xbox and playstation as well. I downloaded a few tools to to confirm upnp function and they all fail on mac and pc.

Running a pcap on a pc i see the traffic multicast traffic sourcing 10.10.10.1 (LAN of opnsense) to 239.255.255.250.

From opnsense i see the traffic sourcing 10.0.0.0/24 towards 239.255.255.250 and being allowed via.a floating rule i have in place.

I also tried sparse mode with an RP  at 10.10.10.2 (l3 switch) as well as dense mode. Does not seem to change the behavior.


I have been able to get more output from the debug but its not particularly helpful.

###With default configuration **listening_ip=vmx1**###

miniupnpd 42377 - - HTTP peer 10.0.0.102:43220 is not from a LAN, closing the connection
miniupnpd 42377 - - level=0 type=20
miniupnpd 42377 - - sdl_index = 2  vmx1:0.50.56.b0.8b.46
miniupnpd 42377 - - ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1 (ver=1)
miniupnpd 42377 - - SSDP M-SEARCH from 10.0.0.151:60280 ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
miniupnpd 42377 - - Single search found
miniupnpd 42377 - - SendSSDPResponse(): 0 bytes to 10.0.0.151:60280 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
USN: uuid:0e92e950-9c91-46f9-7d35-bd43c54af59::urn:schemas-upnp-org:device:InternetGatewayDevice:1
EXT:
SERVER: FreeBSD/13.1-RELEASE UPnP/1.1 MiniUPnPd/2.1.20200510
LOCATION: http://10.10.10.1:2189/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1665333956
BOOTID.UPNP.ORG: 1665333956
CONFIGID.UPNP.ORG: 1337




###After changing to **listening_ip=vmx1/8**###

root@OPNsense:~ # miniupnpd -d -f /var/etc/miniupnpd.conf
miniupnpd 58252 - - version 2.1.20200510 starting UPnP-IGD ext if vmx0 BOOTID=1665334113
miniupnpd 58252 - - HTTP listening on port 2189
miniupnpd 58252 - - no HTTP IPv6 address, disabling IPv6
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43262 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43258 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43260 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43266 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43268 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43264 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43274 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43270 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43278 : GET /WANIPCn.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43276 : GET /WANIPCn.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43280 : GET /WANIPCn.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43286 : GET /WANCfg.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43282 : GET /WANCfg.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43284 : GET /WANCfg.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43290 : GET /L3F.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43292 : GET /L3F.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - HTTP REQUEST from 10.0.0.102:43294 : GET /L3F.xml (HTTP/1.1)
miniupnpd 58252 - - Host: 10.10.10.1:2189
miniupnpd 58252 - - level=0 type=20
miniupnpd 58252 - - sdl_index = 2  vmx1:0.50.56.b0.8b.46
miniupnpd 58252 - - level=0 type=20
miniupnpd 58252 - - sdl_index = 2  vmx1:0.50.56.b0.8b.46
miniupnpd 58252 - - level=0 type=20
miniupnpd 58252 - - sdl_index = 2  vmx1:0.50.56.b0.8b.46


Any thoughts?

**Comment by miniupnp** [comment] 2022-10-09 22:09
Well I don't see any failure in miniupnpd there.
the client is able to discover it and to download the XML service descriptions 
 /rootDesc.xml /WANIPCn.xml  /WANCfg.xml  and /L3F.xml

What are the PC/mac clients you tested ? what are the error messages ?

**Comment by Tawmu** [comment] 2022-10-18 14:44
I'm also seeing something similar, specifically with Teredo networking (which can be tested using the "Xbox Console Companion" app on Windows 11. Miniupnpd adds the appropriate rule when the device is on the same L2 LAN as the firewall but once it's behind a L3 switch with an ssdp relay it stops working. Interestingly the Parsec app seems to work fairly reliably across VLANs - whilst it doesn't confirm what or where the issue is, it doesn't appear as if it's miniupnpd at the moment.

**Comment by miniupnp** [comment] 2024-01-08 00:15
no update, closing.

**Closed by miniupnp** 2024-01-08 00:15 UTC
Labels: miniupnpd, waiting for feedback
